# Use root/example as user/password credentials
version: "3.1"
services:
  # Vue Frontend
  mealie-frontend:
    image: mealie-frontend:dev
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    restart: always
    ports:
      - 9920:8080
    environment:
      VUE_APP_API_BASE_URL: "http://mealie-api:9000"
    volumes:
      - ./frontend/:/app
      - /app/node_modules

  # Fast API
  mealie-api:
    image: mealie-api:dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 9921:9000
    environment:
      TZ: America/Anchorage # Specify Correct Timezone for Date/Time to line up correctly.
      db_username: root
      db_password: example
      db_host: mongo
      db_port: 27017
    volumes:
      - ./mealie:/app

  # Database
  mongo:
    image: mongo
    restart: always
    ports:
      - 9923:27017
    environment:
      TZ: America/Anchorage # Specify Correct Timezone for Date/Time to line up correctly.
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # Database UI
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9922:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
