version: "3.1"
services:
  mealie:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mealie
    restart: always
    ports:
      - 9090:80
    environment:
      db_type: sqlite
