# Use root/example as user/password credentials
# Frontend/Backend Served via the same Uvicorn Server
version: "3.1"
services:
  mealie:
    build:
      context: ./
      dockerfile: Dockerfile.arm
    container_name: mealie
    restart: always
    ports:
      - 9090:80
    environment:
      db_type: sql
    volumes:
      - ./mealie/data/:/app/data
