site_name: Mealie

theme:
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
  favicon: assets/img/favicon.png
  name: material
  icon:
    logo: material/silverware-variant

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - attr_list
  - pymdownx.tabbed
  - pymdownx.superfences

extra_css:
  - assets/stylesheets/custom.css
repo_url: https://github.com/hay-kot/mealie
repo_name: hay-kot/mealie

nav:
  - Home: "index.md"
  - Getting Started:
      - Introduction: "getting-started/introduction.md"
      - Installation: "getting-started/install.md"
      - Updating: "getting-started/updating.md"
      - Working With Recipes: "getting-started/recipes.md"
      - Organizing Recipes: "getting-started/organizing-recipes.md"
      - Planning Meals: "getting-started/meal-planner.md"
      - iOS Shortcuts: "getting-started/ios.md"
      - API Usage: "getting-started/api-usage.md"
      - Site Administration:
          - User Settings: "site-administration/user-settings.md"
          - Site Settings: "site-administration/site-settings.md"
          - Building Pages: "site-administration/building-pages.md"
          - User Management: "site-administration/user-management.md"
          - Backups and Restore: "site-administration/backups-and-exports.md"
          - Recipe Migration: "site-administration/migration-imports.md"
  - API Reference: "api/redoc.md"
  - Contributors Guide:
      - Non-Code: "contributors/non-coders.md"
      - Translating: "contributors/translating.md"
      - Developers Guide:
          - Code Contributions: "contributors/developers-guide/code-contributions.md"
          - Dev Getting Started: "contributors/developers-guide/starting-dev-server.md"
          - Guidelines: "contributors/developers-guide/general-guidelines.md"
  - Development Road Map: "roadmap.md"
  - Change Log:
      - v0.4.0 Authentication: "changelog/v0.4.0.md"
      - v0.3.0 Improvements: "changelog/v0.3.0.md"
      - v0.2.0 Now With Tests!: "changelog/v0.2.0.md"
      - v0.1.0 Beta: "changelog/v0.1.0.md"

